[tool.poetry]
name = "tools"
version = "0.1.0"
description = ""
authors = ["dopefile <merlinincorp@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
passlib = "^1.7.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
